name: Automated Tests with Allure and GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12.5"

      - name: Install Google Chrome
        run: |
          powershell -Command "Invoke-WebRequest -Uri https://dl.google.com/chrome/install/latest/chrome_installer.exe -OutFile chrome_installer.exe"
          powershell -Command "Start-Process chrome_installer.exe -ArgumentList '/silent', '/install' -NoNewWindow -Wait"

      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Scoop
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

      - name: Add Scoop to PATH
        shell: pwsh
        run: |
          $scoop_path = "$env:USERPROFILE\scoop\shims"
          echo "PATH=$env:PATH;$scoop_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Allure
        shell: pwsh
        run: scoop install allure

      - name: Verify Allure Installation
        run: allure --version

      - name: Setup ChromeDriver
        uses: actions/setup-chromedriver@v3
        with:
          chrome-version: 'latest'  # Автоматически устанавливает совместимую версию

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest -v -s -m text --alluredir=allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
          retention-days: 7

  generate-report:
    name: Generate Allure Report
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Scoop
        shell: pwsh
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
          Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')

      - name: Add Scoop to PATH
        shell: pwsh
        run: |
          $scoop_path = "$env:USERPROFILE\scoop\shims"
          echo "PATH=$env:PATH;$scoop_path" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Allure
        shell: pwsh
        run: scoop install allure

      - name: Verify Allure Installation
        run: allure --version

      - name: Download Allure Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 7

  publish-report:
    name: Publish Allure Report to GitHub Pages
    runs-on: ubuntu-latest
    needs: generate-report
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Download Allure Report
        uses: actions/download-artifact@v3
        with:
          name: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      - name: Cleanup Old Reports
        run: |
          # GitHub Pages автоматически хранит только актуальный отчет, дополнительных действий не требуется
          echo "Reports are updated. Old reports are overwritten."
